### ISSUE TITLE
Pevnost držáku konektorů

### ISSUE THREAD

**Issue by kaklik** [bolidozor/RMDS#6]
Aktuální držák konektorů je hodně měkký a není z hlediska pevnosti příliš dobře navržen.  
Zřejmě by bylo vhodné, aby svislá část držící konektory byla zapřena trojúhelníkem do základny.

**Comment by kaklik** [comment]
Tohle je u již u stanice radio-LIBNATOV vyřešeno dobře.

**Comment by kaklik** [comment]
Teď jsem si ale všiml, že k téhle změně zřejmě chybí commit, nebo nevím kde zdroják nového držáku, je? @roman-dvorak

**Comment by roman-dvorak** [comment]
Zdrojaky jsem commitl. 

Ještě by to šlo vyřešít tím, že by se to na placato, protože se to doposavaď lámalo "po vrstvách". Ale myslím, že aktuální vystužení je dostatečné.
